# Generated by Django 2.2 on 2019-04-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nekretnina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(blank=True, max_length=250, verbose_name='Ime')),
                ('sifra', models.PositiveIntegerField(null=True, verbose_name='Šifra')),
                ('ukupna_povrsina', models.PositiveIntegerField(null=True, verbose_name='Ukupna površina [m2]')),
                ('godina_izgradnje_objekta', models.PositiveIntegerField(null=True)),
                ('adresa', models.CharField(blank=True, max_length=250)),
                ('post_broj', models.PositiveIntegerField(null=True, verbose_name='Poštanski broj')),
                ('ostalo', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Nekretnina',
                'verbose_name_plural': 'Nekretnine',
            },
        ),
    ]
